#!/usr/bin/env python

import argparse
import json
import os
import pdb
import sys
from datetime import date

if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog='anomaly_detection')
    parser.add_argument("-v", "--version", help="AnomalyDetection version"
                        , action='store_true', dest='version', default=False)
    subparsers = parser.add_subparsers(dest='cmd', help='sub-commands')

    parser_detection = subparsers.add_parser('druid_anomaly_detection',
                                       help='Detect anomalies based on Druid data')
    parser_detection.add_argument("--config_file_location", type=str,
                            help="Location of job config file")
    parser_detection.add_argument("--data_dir", type=str,
                            help="The path where anomaly output will be written to")
    parser_detection.add_argument("--druid_broker_host", type=str,
                            help="Druid Broker host")
    parser_detection.add_argument("--druid_broker_port", type=str,
                            help="Druid Broker port")
    

    args = parser.parse_args()

    if args.cmd == "druid_anomaly_detection":
        from druid_anomaly_detection import DruidAnomalyDetection

        ad = DruidAnomalyDetection(args.config_file_location, args.data_dir, args.druid_broker_host, args.druid_broker_port)
        ad.init()
        ad.execute()

    if args.version:
        print("version - 1.0.0")
